language: haskell
notifications:
    email: false
env:
    global:
        secure: "VSs2EnclSXbSI1aJXhqYcVpEgxVsVg3RJrGkBPXSleZdUIIvi1T2eg7qFz8DfjCOwMbBjLPCq5+e6Ieq4HexhdxnZYvry4LY39SDelHxajMV+Bh8otO/2+9nPND/D1JQ69Q3D9+gBDBiA59DWezZ+IM3esu67myVrX7yX9S1wSo="
before_install:
    - sudo apt-get install libglade2-0 libglade2-dev libgtk2.0-0 libgtk2.0-common libgtk2.0-dev
    - cabal install gtk2hs-buildtools
    - cabal install haddock
    - cabal install hscolour
after_script:
    - cabal haddock --all --hyperlink-source
    - ./update-gh-pages.sh
